title: LinZhanChong's Homepage
page-top-title: LinZhanChong
top-section-bg-text: Be what you wanna be
home-subtitle: LinZhanChong&ensp;|&ensp;LinZhanChong
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
